@PACKAGE_INIT@

set(RTSPATIAL_VERSION_MAJOR @RTSPATIAL_VERSION_MAJOR@)
set(RTSPATIAL_VERSION_MINOR @RTSPATIAL_VERSION_MINOR@)
set(RTSPATIAL_VERSION_PATCH @RTSPATIAL_VERSION_PATCH@)

set_and_check(RTSPATIAL_INCLUDE_DIR "@PACKAGE_INCLUDE_INSTALL_DIR@")
set_and_check(RTSPATIAL_LIB_DIR "@PACKAGE_LIB_INSTALL_DIR@")

include("${CMAKE_CURRENT_LIST_DIR}/librtspatialTargets.cmake")

set(RTSPATIAL_LIBRARIES rtspatial)

check_required_components(librtspatial)
